framework: mocha
preRun:
  command:
    - yarn install
preMerge:
  pattern:
    - "./test/unit/**/*.test.js"
postMerge:
  pattern:
    - "./test/unit/**/*.test.js"
postRun:
  command:
    - yarn --version
configFile: mocharc.yml
version: 1.0
