version: 2.0
env:
  FORCE_COLOR: 1
  DB: sqlite3
  NODE_ENV: testing
  database__connection__filename: /dev/shm/ghost-test.db
  database__connection__password: root

postMerge:
  preRun:
     command:
        - yarn
  subModules:
      - name: unit-tests   
        framework: mocha  
        path : "./"
        pattern:
          - "./test/unit/**/*.test.js"
        configFile : mocharc.yml
        
      - name: integration-tests   
        framework: mocha   
        path : "./"
        pattern: 
          - "./test/integration/**/*.test.js"
        configFile : mocharc.yml
