framework: mocha
preRun:
  command:
    - yarn setup
preMerge:
  pattern:
    - "./test/{unit,integration}/**/*.test.js"
postMerge:
  pattern:
    - "./test/{unit,integration}/**/*.test.js"
postRun:
  command:
    - yarn --version
configFile: mocharc.yml
version: 1.0.0
